[build]
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

# Form handling
[forms]
  [forms.settings]
    spam_filter = true

# Redirects
[[redirects]]
  from = "/join"
  to = "/add-profile.html"
  status = 301

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
