[build]
  publish = "public"

[build.environment]
  NODE_VERSION = "22"

# Form handling
[[forms]]
  name = "mentors"

[[forms]]
  name = "mentees"

[[forms]]
  name = "testimonials"

[[forms]]
  name = "contact"

[forms.settings]
  spam_filter = true

# Redirects
[[redirects]]
  from = "/join"
  to = "/add-profile.html"
  status = 301

[[redirects]]
  from = "/register"
  to = "/add-profile.html"
  status = 301

[[redirects]]
  from = "/apply"
  to = "/add-profile.html"
  status = 301

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src 'self' https: data:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' https:; connect-src 'self' https:;"

# Cache headers for performance
[[headers]]
  for = "/src/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/src/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/src/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
