[build]
  publish = "public"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/join"
  to = "/add-profile.html"
  status = 301

[[redirects]]
  from = "/register"
  to = "/add-profile.html"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
